swagger: "2.0"
info:
  version: "1.0.0"
  title: "Login Page"
  description: |
    <style>
      body {
        font-family: Arial, sans-serif;
        background-color: #f4f4f4;
      }
      .login-container {
        width: 300px;
        margin: 100px auto;
        padding: 20px;
        background: #fff;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        border-radius: 8px;
      }
      .login-container h2 {
        text-align: center;
        color: #333;
      }
      .form-group {
        margin-bottom: 15px;
      }
      .form-group label {
        display: block;
        font-weight: bold;
      }
      .form-group input {
        width: 100%;
        padding: 8px;
        margin-top: 5px;
        border: 1px solid #ccc;
        border-radius: 4px;
      }
      .button-group {
        display: flex;
        justify-content: space-between;
      }
      .btn {
        width: 48%;
        padding: 10px;
        border: none;
        color: #fff;
        cursor: pointer;
        border-radius: 4px;
      }
      .btn-signin {
        background-color: #007bff;
      }
      .btn-forgot {
        background-color: #17a2b8;
      }
    </style>
    <div class="login-container">
      <h2>Login</h2>
      <form action="https
